### ISSUE TITLE
I'm getting multiple errors.

### ISSUE THREAD

**Issue by s-inactive** [Galactic647/Tyrano-Save-Reader#1]
Hi, Galactic647.  Thanks so much for this tool.
I'm trying to change values in a game that doesn't save to the hard disk by default, and when it does, it ends with the extension "save".  I know for a fact that it is tyrano (I've used online save editors before).  When I change the extension to "sav", your tool converts it successfully though the game refuses to load it "the save data is old or corrupted".  When I switch to monitoring, I get this:
[INFO] [monitor.py:78] No template found
[INFO] [monitor.py:93] Checking integrity...
[ERROR] [monitor.py:96] Integrity check failed
Original source: 61b251e1c891546eb36511485c31d4e004c668631cf549f0e2ac82ff9dcfdbb6
Repacked source: 5b3d2af3bad8e80463486e67c53565d4af0153d5f5cb21e751a17b8968c23307
[INFO] [monitor.py:99] Running difference check...
[CRITICAL] [monitor.py:227] Critical error encountered, below is the traceback
[ERROR] [monitor.py:228] local variable 'idx_range' referenced before assignment
Traceback (most recent call last):
  File "monitor.py", line 223, in <module>
  File "monitor.py", line 105, in main
  File "core\savparser.py", line 140, in difference_highlight
  File "core\savparser.py", line 97, in _highlight
UnboundLocalError: local variable 'idx_range' referenced before assignment
Using online tools is rather tedious, I wanted to make a template for all the values I need.  Is this fixable?
![Integrity Check](https://github.com/user-attachments/assets/eb3161c9-a492-4281-8010-ff3a131e2685)

**Comment by Galactic647** [comment]
The first error is I would say uncommon but the solution is quite easy, though that's not the main problem here, It's the first time I have the difference check function failed, so not sure what happen here.

Can you send me one of the save file that gives that error?, I'll check it out in the morning, shouldn't be too hard I think.

**Comment by s-inactive** [comment]
Okay.
I did try to check why it corrupted when I converted, this is what I got:
1. Converting it to .json proceeded without errors, it was converting it back to sav that had a problem.  Maybe because it was a "save" file instead?
2. Trying to convert the "save" file edited using online tools always resulted in an error of some kind.
3. While testing some things out, the game actually accepted the unconverted .json file.

I'll attach the save file even though my problem is (technically) fixed.  (Be warned, it is one weird game).  Though it has an online version, I use the offline one.
[Town Hall(14_10_2024_8_26_53).zip](https://github.com/user-attachments/files/17359610/Town.Hall.14_10_2024_8_26_53.zip)

**Comment by Galactic647** [comment]
So the monitor script will only work if the save file passes the **integrity check**. The integrity check itself is basically the script will try to convert the save file to json and convert it back to sav, then it will check the hash signature of both files and if it matches, only then it will work.

So I do recommend checking if the script is working properly by running it on the monitor script first, since it's the only script that has an integrity check.

I'll update when I'm done fixing it. And thanks for the save file.

**Comment by Galactic647** [comment]
> Okay. I did try to check why it corrupted when I converted, this is what I got:
> 
> 1. Converting it to .json proceeded without errors, it was converting it back to sav that had a problem.  Maybe because it was a "save" file instead?
> 2. Trying to convert the "save" file edited using online tools always resulted in an error of some kind.
> 3. While testing some things out, the game actually accepted the unconverted .json file.
> 
> I'll attach the save file even though my problem is (technically) fixed. (Be warned, it is one weird game). Though it has an online version, I use the offline one. [Town Hall(14_10_2024_8_26_53).zip](https://github.com/user-attachments/files/17359610/Town.Hall.14_10_2024_8_26_53.zip)

Is this save file the original one from the game or is it the one converted by the script?.

This is how an actual .sav file should look like
![image](https://github.com/user-attachments/assets/a2298972-7382-4ace-903d-5403d4996ab8)

However yours is already in json
![image](https://github.com/user-attachments/assets/acd5f67f-1d9a-4064-a94f-0b06f941f121)

**Comment by s-inactive** [comment]
Oh.  So that's why it accepted the .json file.  Can't believe I didn't check if the save was encrypted.
It seems that is why it corrupts when I change it back to save.
Sorry for bothering you and thanks for your time.

**Comment by Galactic647** [comment]
No prob
